// <auto-generated />
namespace DataAccess.Migrations
{
    using System.CodeDom.Compiler;
    using System.Data.Entity.Migrations;
    using System.Data.Entity.Migrations.Infrastructure;
    using System.Resources;
    
    [GeneratedCode("EntityFramework.Migrations", "6.2.0-beta1-60406")]
    public sealed partial class ColunadeObservaçõesdapessoa : IMigrationMetadata
    {
        private readonly ResourceManager Resources = new ResourceManager(typeof(ColunadeObservaçõesdapessoa));
        
        string IMigrationMetadata.Id
        {
            get { return "201711191731441_Coluna de Observações da pessoa"; }
        }
        
        string IMigrationMetadata.Source
        {
            get { return null; }
        }
        
        string IMigrationMetadata.Target
        {
            get { return Resources.GetString("Target"); }
        }
    }
}
